
#================License Verify 证书验证配置E===============#

#证书主题
license:
  verify:
    subject: zenyone
#公钥库证书条目别名
    publicAlias: publicCert
#证书公钥库存储路径(公钥库可以公开出去，但是私有密钥库一定要自己保存好，即私有密钥库要保存在creator模块中)
    publicKeysStorePath: /publicCerts.keystore
#证书公钥库访问密码
    storePass: pubwd@1302zlm
#证书存放路径
    licensePath: classpath:license.lic